apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresser-deployment
  labels:
    app: stresser
spec:
  replicas: 0
  selector:
    matchLabels:
      app: stresser
  template:
    metadata:
      labels:
        app: stresser
    spec:
      containers:
      - name: stresser
        image: anbossar.azurecr.io/stresser:latest
        args: ["--cpu", "10",  "--io", "10", "--vm", "4", "--vm-bytes", "512M", "--hdd", "2"]