on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n anbosssarcr -g anbosssarcr8d51-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n anbosssarcr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n anbosssarcr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n anbosssarcr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: anbosssarcr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t anbosssarcr.azurecr.io/anbossarakscluster01:${{ github.sha }}
        docker push anbosssarcr.azurecr.io/anbossarakscluster01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_anbossarakscluster01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep anbossarakscluster019eff | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace anbossarakscluster019eff`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: anbossarakscluster019eff
        container-registry-url: anbosssarcr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: anbossarakscdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: anbossarakscluster019eff
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          anbosssarcr.azurecr.io/anbossarakscluster01:${{ github.sha }}
        imagepullsecrets: |
          anbossarakscdockerauth